# Generated by tools/gen_ros_recipes.py from rosdistro. Do not edit by hand.
import glob
import os
import sys
from conan import ConanFile
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import get, replace_in_file
from conan.tools.gnu import PkgConfigDeps
from conan.tools.microsoft import VCVars


class RosPackageConan(ConanFile):
    """package.xml build_type: ament_cmake"""

    name = "theora_image_transport"
    version = "5.1.2"
    user = "ros-kilted"
    license = 'BSD'
    settings = "os", "compiler", "build_type", "arch"

    options = {"python_version": ["ANY"]}
    default_options = {
        "python_version": f"{sys.version_info.major}.{sys.version_info.minor}",
    }

    def layout(self):
        cmake_layout(self, src_folder="src")

    def requirements(self):
        self.requires(
            "ament_cmake/2.7.5@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "cv_bridge/4.1.0@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "image_transport/6.1.4@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "ogg/1.3.5",
            transitive_headers=True,
            transitive_libs=True,
        )
        self.requires(
            "opencv/4.12.0",
            transitive_headers=True,
            transitive_libs=True,
            options={"aruco": "True"},
        )
        self.requires(
            "theora/1.1.1",
            transitive_headers=True,
            transitive_libs=True,
        )
        self.requires(
            "pluginlib/5.6.3@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "rclcpp/29.5.8@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "rcutils/6.9.10@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "rosidl_default_generators/1.7.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "rosidl_default_runtime/1.7.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "sensor_msgs/5.5.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "std_msgs/5.5.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "catkin_pkg/1.1.0@ros-kilted",
            run=True,
        )
        self.requires(
            "setuptools/75.8.0@ros-kilted",
            run=True,
        )

    def build_requirements(self):
        self.tool_requires("pkgconf/2.2.0")

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        replace_in_file(
            self,
            os.path.join(self.source_folder, 'CMakeLists.txt'),
            'pkg_check_modules(PC_THEORADEC REQUIRED theoradec)',
            'pkg_check_modules(PC_THEORADEC REQUIRED theoradec)\ninclude_directories(${PC_OGG_INCLUDE_DIRS} ${PC_THEORA_INCLUDE_DIRS}\n  ${PC_THEORAENC_INCLUDE_DIRS} ${PC_THEORADEC_INCLUDE_DIRS})\nlink_directories(${PC_OGG_LIBRARY_DIRS} ${PC_THEORA_LIBRARY_DIRS}\n  ${PC_THEORAENC_LIBRARY_DIRS} ${PC_THEORADEC_LIBRARY_DIRS})',
        )

    def generate(self):
        CMakeDeps(self).generate()
        PkgConfigDeps(self).generate()

        python = self.conf.get("user.ros2:python", check_type=str) or sys.executable
        python = python.replace("\\", "/")
        python_root = python.rsplit("/", 1)[0]
        tc = CMakeToolchain(self)
        tc.variables["BUILD_TESTING"] = False
        tc.variables["Python3_EXECUTABLE"] = python
        tc.variables["Python3_ROOT_DIR"] = python_root
        tc.variables["Python_EXECUTABLE"] = python
        tc.variables["Python_ROOT_DIR"] = python_root
        tc.generate()
        VCVars(self).generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        pkg = self.package_folder
        # ament: executables in bin, MODULE/SHARED plugins in lib.
        self.cpp_info.bindirs = ["bin", "lib"]
        self.cpp_info.builddirs.append(pkg)
        self.cpp_info.builddirs.append(os.path.join(pkg, "share", self.name, "cmake"))
        site_packages = [os.path.join(pkg, "Lib", "site-packages")] + sorted(
            glob.glob(os.path.join(pkg, "lib", "python*", "site-packages")))
        # Not in buildenv: CMakeToolchain already puts every dependency's builddirs in
        # CMAKE_PREFIX_PATH inside conan_toolchain.cmake, a file with no length limit,
        # and one entry per package does not fit in an environment at distro scale.
        self.runenv_info.prepend_path("CMAKE_PREFIX_PATH", pkg)
        for env in (self.buildenv_info, self.runenv_info):
            env.prepend_path("AMENT_PREFIX_PATH", pkg)
            for site in site_packages:
                env.prepend_path("PYTHONPATH", site)
