# Generated by tools/gen_ros_recipes.py from rosdistro. Do not edit by hand.
import glob
import os
import sys

from conan import ConanFile
from conan.tools.layout import basic_layout


class RosPipPackageConan(ConanFile):
    """PyPI distribution backing a rosdep key. Pure python, shared via PYTHONPATH."""

    name = "packaging"
    version = "24.2"
    user = "ros-kilted"
    license = 'unknown'
    settings = "os", "arch"

    def layout(self):
        basic_layout(self)

    def package_id(self):
        # Pure python, no extension module: one binary per platform is enough.
        del self.info.settings.arch

    def package(self):
        # Dependencies come along: they are pure python too and nothing else in the
        # graph provides them. Override the interpreter with -c user.ros2:python=<path>.
        python = self.conf.get("user.ros2:python", check_type=str) or sys.executable
        # --ignore-installed is not optional: --prefix does not isolate pip from the
        # interpreter running it, so pip would either skip an already satisfied
        # requirement, packaging nothing, or uninstall the ambient copy to make room
        # for a different version.
        self.run(
            f'"{python}" -m pip install packaging==24.2 --no-compile '
            f'--ignore-installed --no-warn-script-location '
            f'--prefix "{self.package_folder}"'
        )

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        self.cpp_info.includedirs = []
        self.cpp_info.libdirs = []
        # No native runtime library: do not spend PATH on an empty bin/.
        self.cpp_info.bindirs = []
        pkg = self.package_folder
        site_packages = [os.path.join(pkg, "Lib", "site-packages")] + sorted(
            glob.glob(os.path.join(pkg, "lib", "python*", "site-packages")))
        for env in (self.buildenv_info, self.runenv_info):
            for site in site_packages:
                env.prepend_path("PYTHONPATH", site)
            env.prepend_path("PATH", os.path.join(pkg, "bin"))
            env.prepend_path("PATH", os.path.join(pkg, "Scripts"))
