# Generated by tools/gen_ros_recipes.py from rosdistro. Do not edit by hand.
import glob
import os
import sys
from conan import ConanFile
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import get


class RosPackageConan(ConanFile):
    """package.xml build_type: ament_cmake"""

    name = "ros_base"
    version = "0.12.0"
    user = "ros-kilted"
    license = 'Apache License 2.0'
    settings = "os", "compiler", "build_type", "arch"

    def layout(self):
        cmake_layout(self, src_folder="src")

    def package_id(self):
        # project(... NONE): CMake loads no compiler, this installs macros only.
        del self.info.settings.compiler
        del self.info.settings.build_type
        del self.info.settings.arch

    def requirements(self):
        self.requires(
            "ament_cmake/2.7.5@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "geometry2/0.41.7@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "kdl_parser/2.12.1@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "robot_state_publisher/3.4.3@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "ros_core/0.12.0@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "rosbag2/0.32.0@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "urdf/2.12.3@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "catkin_pkg/1.1.0@ros-kilted",
            run=True,
        )
        self.requires(
            "setuptools/75.8.0@ros-kilted",
            run=True,
        )

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)

    def generate(self):
        deps = CMakeDeps(self)
        deps.set_property("lz4", "cmake_target_name", "LZ4::lz4")
        deps.set_property("zstd", "cmake_target_name", "zstd::zstd")
        deps.generate()

        python = self.conf.get("user.ros2:python", check_type=str) or sys.executable
        python = python.replace("\\", "/")
        python_root = python.rsplit("/", 1)[0]
        tc = CMakeToolchain(self)
        tc.variables["BUILD_TESTING"] = False
        tc.variables["Python3_EXECUTABLE"] = python
        tc.variables["Python3_ROOT_DIR"] = python_root
        tc.variables["Python_EXECUTABLE"] = python
        tc.variables["Python_ROOT_DIR"] = python_root
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        pkg = self.package_folder
        self.cpp_info.builddirs.append(pkg)
        self.cpp_info.builddirs.append(os.path.join(pkg, "share", self.name, "cmake"))
        site_packages = [os.path.join(pkg, "Lib", "site-packages")] + sorted(
            glob.glob(os.path.join(pkg, "lib", "python*", "site-packages")))
        # Not in buildenv: CMakeToolchain already puts every dependency's builddirs in
        # CMAKE_PREFIX_PATH inside conan_toolchain.cmake, a file with no length limit,
        # and one entry per package does not fit in an environment at distro scale.
        self.runenv_info.prepend_path("CMAKE_PREFIX_PATH", pkg)
        for env in (self.buildenv_info, self.runenv_info):
            env.prepend_path("AMENT_PREFIX_PATH", pkg)
            for site in site_packages:
                env.prepend_path("PYTHONPATH", site)
