# Generated by tools/gen_ros_recipes.py from rosdistro. Do not edit by hand.
import glob
import os
import sys
from conan import ConanFile
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import get
from conan.tools.microsoft import VCVars


class RosPackageConan(ConanFile):
    """package.xml build_type: cmake"""

    name = "fastdds"
    version = "3.2.4"
    user = "ros-kilted"
    license = 'Apache 2.0'
    settings = "os", "compiler", "build_type", "arch"

    def layout(self):
        cmake_layout(self, src_folder="src")

    def requirements(self):
        self.requires(
            "asio/1.28.1",
            transitive_headers=True,
            transitive_libs=True,
        )
        self.requires(
            "fastcdr/2.3.6@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "foonathan_memory_vendor/1.3.1@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "openssl/[>=3.3 <4]",
            transitive_headers=True,
            transitive_libs=True,
        )
        self.requires(
            "tinyxml2/10.0.0",
            transitive_headers=True,
            transitive_libs=True,
        )

    def build_requirements(self):
        self.tool_requires("cmake/3.29.3")

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)

    def generate(self):
        CMakeDeps(self).generate()

        python = self.conf.get("user.ros2:python", check_type=str) or sys.executable
        python = python.replace("\\", "/")
        python_root = python.rsplit("/", 1)[0]
        tc = CMakeToolchain(self)
        tc.variables["BUILD_TESTING"] = False
        tc.variables["Python3_EXECUTABLE"] = python
        tc.variables["Python3_ROOT_DIR"] = python_root
        tc.variables["Python_EXECUTABLE"] = python
        tc.variables["Python_ROOT_DIR"] = python_root
        tc.variables["Asio_INCLUDE_DIR"] = self.dependencies["asio"].cpp_info.includedirs[0].replace("\\", "/")
        tc.variables["TINYXML2_INCLUDE_DIR"] = self.dependencies["tinyxml2"].cpp_info.includedirs[0].replace("\\", "/")
        tc.variables["TINYXML2_LIBRARY"] = self.dependencies["tinyxml2"].cpp_info.get_property("cmake_target_name")
        tc.generate()
        VCVars(self).generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        pkg = self.package_folder
        self.cpp_info.builddirs.append(pkg)
        self.cpp_info.builddirs.append(os.path.join(pkg, "share", self.name, "cmake"))
        self.cpp_info.builddirs.append(os.path.join(pkg, "lib", "cmake", self.name))
        site_packages = [os.path.join(pkg, "Lib", "site-packages")] + sorted(
            glob.glob(os.path.join(pkg, "lib", "python*", "site-packages")))
        # Not in buildenv: CMakeToolchain already puts every dependency's builddirs in
        # CMAKE_PREFIX_PATH inside conan_toolchain.cmake, a file with no length limit,
        # and one entry per package does not fit in an environment at distro scale.
        self.runenv_info.prepend_path("CMAKE_PREFIX_PATH", pkg)
        for env in (self.buildenv_info, self.runenv_info):
            for site in site_packages:
                env.prepend_path("PYTHONPATH", site)
