# Generated by tools/gen_ros_recipes.py from rosdistro. Do not edit by hand.
import glob
import os
import sys
from conan import ConanFile
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import get, replace_in_file
from conan.tools.microsoft import VCVars


class RosPackageConan(ConanFile):
    """package.xml build_type: ament_cmake"""

    name = "nav2_util"
    version = "1.4.2"
    user = "ros-kilted"
    license = 'Apache-2.0'
    settings = "os", "compiler", "build_type", "arch"
    package_type = "shared-library"

    def layout(self):
        cmake_layout(self, src_folder="src")

    def requirements(self):
        self.requires(
            "ament_cmake/2.7.5@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "bond/4.3.0@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "bondcpp/4.3.0@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "builtin_interfaces/2.3.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "geometry_msgs/5.5.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "lifecycle_msgs/2.3.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "nav2_common/1.4.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "nav2_msgs/1.4.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "nav_msgs/5.5.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "pluginlib/5.6.3@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "rcl_interfaces/2.3.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "rclcpp/29.5.8@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "rclcpp_action/29.5.8@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "rclcpp_lifecycle/29.5.8@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "std_msgs/5.5.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "tf2/0.41.7@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "tf2_geometry_msgs/0.41.7@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "tf2_msgs/0.41.7@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "tf2_ros/0.41.7@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "catkin_pkg/1.1.0@ros-kilted",
            run=True,
        )
        self.requires(
            "setuptools/75.8.0@ros-kilted",
            run=True,
        )

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        replace_in_file(
            self,
            os.path.join(self.source_folder, 'src/node_utils.cpp'),
            'void setSoftRealTimePriority()\n{\n  sched_param sch;\n  sch.sched_priority = 49;\n  if (sched_setscheduler(0, SCHED_FIFO, &sch) == -1) {\n    std::string errmsg(\n      "Cannot set as real-time thread. Users must set: <username> hard rtprio 99 and "\n      "<username> soft rtprio 99 in /etc/security/limits.conf to enable "\n      "realtime prioritization! Error: ");\n    throw std::runtime_error(errmsg + std::strerror(errno));\n  }\n}',
            'void setSoftRealTimePriority()\n{\n#if defined(__APPLE__) || defined(_WIN32)\n  throw std::runtime_error(\n    "Setting priority as real-time thread is currently only supported on Linux.");\n#else\n  sched_param sch;\n  sch.sched_priority = 49;\n  if (sched_setscheduler(0, SCHED_FIFO, &sch) == -1) {\n    std::string errmsg(\n      "Cannot set as real-time thread. Users must set: <username> hard rtprio 99 and "\n      "<username> soft rtprio 99 in /etc/security/limits.conf to enable "\n      "realtime prioritization! Error: ");\n    throw std::runtime_error(errmsg + std::strerror(errno));\n  }\n#endif\n}',
        )

    def generate(self):
        CMakeDeps(self).generate()

        python = self.conf.get("user.ros2:python", check_type=str) or sys.executable
        python = python.replace("\\", "/")
        python_root = python.rsplit("/", 1)[0]
        tc = CMakeToolchain(self)
        tc.variables["BUILD_TESTING"] = False
        tc.variables["Python3_EXECUTABLE"] = python
        tc.variables["Python3_ROOT_DIR"] = python_root
        tc.variables["Python_EXECUTABLE"] = python
        tc.variables["Python_ROOT_DIR"] = python_root
        tc.generate()
        VCVars(self).generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        pkg = self.package_folder
        # ament on Windows installs RUNTIME (exe and DLL) under bin/.
        self.cpp_info.bindirs = ["bin"]
        self.cpp_info.builddirs.append(pkg)
        self.cpp_info.builddirs.append(os.path.join(pkg, "share", self.name, "cmake"))
        site_packages = [os.path.join(pkg, "Lib", "site-packages")] + sorted(
            glob.glob(os.path.join(pkg, "lib", "python*", "site-packages")))
        # Not in buildenv: CMakeToolchain already puts every dependency's builddirs in
        # CMAKE_PREFIX_PATH inside conan_toolchain.cmake, a file with no length limit,
        # and one entry per package does not fit in an environment at distro scale.
        self.runenv_info.prepend_path("CMAKE_PREFIX_PATH", pkg)
        for env in (self.buildenv_info, self.runenv_info):
            env.prepend_path("AMENT_PREFIX_PATH", pkg)
            for site in site_packages:
                env.prepend_path("PYTHONPATH", site)
