# Generated by tools/gen_ros_recipes.py from rosdistro. Do not edit by hand.
import glob
import os
import sys

from conan import ConanFile
from conan.tools.files import get
from conan.tools.layout import basic_layout


class RosPackageConan(ConanFile):
    """package.xml build_type: ament_python"""

    name = "examples_rclpy_minimal_service"
    version = "0.20.6"
    user = "ros-kilted"
    license = 'Apache License 2.0'
    settings = "os", "arch"

    def layout(self):
        basic_layout(self, src_folder="src")

    def package_id(self):
        # Pure python, no extension module: one binary per platform is enough.
        del self.info.settings.arch

    def requirements(self):
        self.requires(
            "example_interfaces/0.13.1@ros-kilted",
            run=True,
        )
        self.requires(
            "rclpy/9.1.5@ros-kilted",
            run=True,
        )
        self.requires(
            "std_msgs/5.5.2@ros-kilted",
            run=True,
        )
        self.requires(
            "setuptools/75.8.0@ros-kilted",
            run=True,
        )

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)

    def package(self):
        # setuptools does the whole build; --no-build-isolation keeps it offline, so the
        # interpreter needs setuptools. Override it with -c user.ros2:python=<path>.
        # --no-compile: .pyc are tagged for the packaging interpreter, not the ROS one.
        python = self.conf.get("user.ros2:python", check_type=str) or sys.executable
        self.run(
            f'"{python}" -m pip install . --no-deps --no-build-isolation --no-compile '
            f'--ignore-installed --no-warn-script-location '
            f'--prefix "{self.package_folder}"',
            cwd=self.source_folder,
        )

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        self.cpp_info.includedirs = []
        self.cpp_info.libdirs = []
        pkg = self.package_folder
        site_packages = [os.path.join(pkg, "Lib", "site-packages")] + sorted(
            glob.glob(os.path.join(pkg, "lib", "python*", "site-packages")))
        for env in (self.buildenv_info, self.runenv_info):
            env.prepend_path("AMENT_PREFIX_PATH", pkg)
            for site in site_packages:
                env.prepend_path("PYTHONPATH", site)
            env.prepend_path("PATH", os.path.join(pkg, "bin"))
            env.prepend_path("PATH", os.path.join(pkg, "Scripts"))
