# Generated by tools/gen_ros_recipes.py from rosdistro. Do not edit by hand.
import glob
import os
import sys
from conan import ConanFile
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import get, replace_in_file
from conan.tools.microsoft import VCVars


class RosPackageConan(ConanFile):
    """package.xml build_type: ament_cmake"""

    name = "cv_bridge"
    version = "4.1.0"
    user = "ros-kilted"
    license = 'Apache License 2.0'
    settings = "os", "compiler", "build_type", "arch"

    def layout(self):
        cmake_layout(self, src_folder="src")

    def requirements(self):
        self.requires(
            "ament_cmake_ros/0.14.7@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "ament_index_python/1.11.4@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "boost/1.83.0",
            transitive_headers=True,
            transitive_libs=True,
            options={"without_python": "False"},
        )
        self.requires(
            "opencv/4.12.0",
            transitive_headers=True,
            transitive_libs=True,
            options={"aruco": "True"},
        )
        self.requires(
            "numpy/2.3.2@ros-kilted",
            run=True,
        )
        self.requires(
            "python_cmake_module/0.12.0@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "rclcpp/29.5.8@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "rcpputils/2.13.5@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "sensor_msgs/5.5.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "catkin_pkg/1.1.0@ros-kilted",
            run=True,
        )
        self.requires(
            "setuptools/75.8.0@ros-kilted",
            run=True,
        )

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        replace_in_file(
            self,
            os.path.join(self.source_folder, 'CMakeLists.txt'),
            '  find_package(Python3 REQUIRED COMPONENTS Development NumPy)\n  find_package(Boost QUIET)\n  if(Boost_VERSION_STRING VERSION_LESS "1.67")\n    # This is a bit of a hack to suppress a warning\n    #   No header defined for python3; skipping header check\n    # Which should only affect Boost versions < 1.67\n    # Resolution for newer versions:\n    #  https://gitlab.kitware.com/cmake/cmake/issues/16391\n    set(_Boost_PYTHON3_HEADERS "boost/python.hpp")\n    find_package(Boost REQUIRED COMPONENTS python3)\n    set(boost_python_target "Boost::python3")\n  else()\n    find_package(Boost REQUIRED COMPONENTS python${Python3_VERSION_MAJOR}${Python3_VERSION_MINOR})\n    set(boost_python_target "Boost::python${Python3_VERSION_MAJOR}${Python3_VERSION_MINOR}")\n  endif()',
            '  find_package(Python3 REQUIRED COMPONENTS Development NumPy)\n  find_package(Boost REQUIRED CONFIG COMPONENTS python)\n  set(boost_python_target "Boost::python")',
        )

    def generate(self):
        CMakeDeps(self).generate()

        python = self.conf.get("user.ros2:python", check_type=str) or sys.executable
        python = python.replace("\\", "/")
        python_root = python.rsplit("/", 1)[0]
        tc = CMakeToolchain(self)
        tc.variables["BUILD_TESTING"] = False
        tc.variables["Python3_EXECUTABLE"] = python
        tc.variables["Python3_ROOT_DIR"] = python_root
        tc.variables["Python_EXECUTABLE"] = python
        tc.variables["Python_ROOT_DIR"] = python_root
        tc.generate()
        VCVars(self).generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        pkg = self.package_folder
        self.cpp_info.builddirs.append(pkg)
        self.cpp_info.builddirs.append(os.path.join(pkg, "share", self.name, "cmake"))
        site_packages = [os.path.join(pkg, "Lib", "site-packages")] + sorted(
            glob.glob(os.path.join(pkg, "lib", "python*", "site-packages")))
        # Not in buildenv: CMakeToolchain already puts every dependency's builddirs in
        # CMAKE_PREFIX_PATH inside conan_toolchain.cmake, a file with no length limit,
        # and one entry per package does not fit in an environment at distro scale.
        self.runenv_info.prepend_path("CMAKE_PREFIX_PATH", pkg)
        for env in (self.buildenv_info, self.runenv_info):
            env.prepend_path("AMENT_PREFIX_PATH", pkg)
            for site in site_packages:
                env.prepend_path("PYTHONPATH", site)
