# Generated by tools/gen_ros_recipes.py from rosdistro. Do not edit by hand.
import glob
import os
import sys
from conan import ConanFile
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import get, replace_in_file
from conan.tools.microsoft import VCVars


class RosPackageConan(ConanFile):
    """package.xml build_type: ament_cmake"""

    name = "laser_filters"
    version = "2.2.3"
    user = "ros-kilted"
    license = 'BSD'
    settings = "os", "compiler", "build_type", "arch"

    def layout(self):
        cmake_layout(self, src_folder="src")

    def requirements(self):
        self.requires(
            "ament_cmake_auto/2.7.5@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "angles/1.16.1@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "diagnostic_msgs/5.5.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "diagnostic_updater/4.3.7@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "filters/2.2.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "laser_geometry/2.10.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "message_filters/7.1.10@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "pluginlib/5.6.3@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "rclcpp/29.5.8@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "rclcpp_components/29.5.8@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "rclcpp_lifecycle/29.5.8@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "sensor_msgs/5.5.2@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "tf2/0.41.7@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "tf2_geometry_msgs/0.41.7@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "tf2_kdl/0.41.7@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "tf2_ros/0.41.7@ros-kilted",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "catkin_pkg/1.1.0@ros-kilted",
            run=True,
        )
        self.requires(
            "setuptools/75.8.0@ros-kilted",
            run=True,
        )

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        replace_in_file(
            self,
            os.path.join(self.source_folder, 'include/laser_filters/binning_filter.h'),
            '  uint num_bins_;',
            '  unsigned int num_bins_;',
        )

    def generate(self):
        CMakeDeps(self).generate()

        python = self.conf.get("user.ros2:python", check_type=str) or sys.executable
        python = python.replace("\\", "/")
        python_root = python.rsplit("/", 1)[0]
        tc = CMakeToolchain(self)
        tc.variables["BUILD_TESTING"] = False
        tc.variables["Python3_EXECUTABLE"] = python
        tc.variables["Python3_ROOT_DIR"] = python_root
        tc.variables["Python_EXECUTABLE"] = python
        tc.variables["Python_ROOT_DIR"] = python_root
        tc.variables["CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS"] = 'ON'
        tc.generate()
        VCVars(self).generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        pkg = self.package_folder
        # ament: executables in bin, MODULE/SHARED plugins in lib.
        self.cpp_info.bindirs = ["bin", "lib"]
        self.cpp_info.builddirs.append(pkg)
        self.cpp_info.builddirs.append(os.path.join(pkg, "share", self.name, "cmake"))
        site_packages = [os.path.join(pkg, "Lib", "site-packages")] + sorted(
            glob.glob(os.path.join(pkg, "lib", "python*", "site-packages")))
        # Not in buildenv: CMakeToolchain already puts every dependency's builddirs in
        # CMAKE_PREFIX_PATH inside conan_toolchain.cmake, a file with no length limit,
        # and one entry per package does not fit in an environment at distro scale.
        self.runenv_info.prepend_path("CMAKE_PREFIX_PATH", pkg)
        for env in (self.buildenv_info, self.runenv_info):
            env.prepend_path("AMENT_PREFIX_PATH", pkg)
            for site in site_packages:
                env.prepend_path("PYTHONPATH", site)
