# Generated by tools/gen_ros_recipes.py from rosdistro. Do not edit by hand.
import glob
import os
import sys

from conan import ConanFile
from conan.tools.layout import basic_layout


class RosPipPackageConan(ConanFile):
    """PyPI distribution backing a rosdep key. Pure python, shared via PYTHONPATH."""

    name = "vcstool"
    version = "0.3.0"
    user = "ros-kilted"
    license = 'unknown'
    settings = "os", "arch"

    def layout(self):
        basic_layout(self)

    def package_id(self):
        # Pure python, no extension module: one binary per platform is enough.
        del self.info.settings.arch

    def package(self):
        # Dependencies come along: they are pure python too and nothing else in the
        # graph provides them. Override the interpreter with -c user.ros2:python=<path>.
        python = self.conf.get("user.ros2:python", check_type=str) or sys.executable
        # --ignore-installed is not optional: --prefix does not isolate pip from the
        # interpreter running it, so pip would either skip an already satisfied
        # requirement, packaging nothing, or uninstall the ambient copy to make room
        # for a different version.
        self.run(
            f'"{python}" -m pip install vcstool==0.3.0 --no-compile '
            f'--ignore-installed --no-warn-script-location '
            f'--prefix "{self.package_folder}"'
        )

        # The distlib .exe launcher is a second console process. It forwards stdout
        # to the caller, and Windows still opens an empty console for it.
        # Run the interpreter in the caller's console.
        if self.settings.os == "Windows":
            import io
            import zipfile
            scripts = os.path.join(self.package_folder, "Scripts")
            if os.path.isdir(scripts):
                for name in os.listdir(scripts):
                    if not name.endswith(".exe"):
                        continue
                    exe = os.path.join(scripts, name)
                    blob = open(exe, "rb").read()
                    start = blob.rfind(b"#!")
                    zip_at = blob.find(b"PK\x03\x04", 0 if start < 0 else start)
                    if start < 0 or zip_at < 0:
                        continue
                    python = blob[start + 2:blob.find(b"\n", start)].decode().strip().strip('"')
                    with zipfile.ZipFile(io.BytesIO(blob[zip_at:])) as archive:
                        source = archive.read("__main__.py")
                    stem = name[:-4]
                    script = os.path.join(scripts, stem + "-script.py")
                    with open(script, "wb") as handle:
                        handle.write(source)
                    cmd = os.path.join(scripts, stem + ".cmd")
                    line = '@echo off\r\n"' + python + '" "%~dp0' + stem + '-script.py" %*\r\n'
                    with open(cmd, "w", newline="\r\n", encoding="utf-8") as handle:
                        handle.write(line)
                    os.remove(exe)

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        self.cpp_info.includedirs = []
        self.cpp_info.libdirs = []
        # No native runtime library: do not spend PATH on an empty bin/.
        self.cpp_info.bindirs = []
        pkg = self.package_folder
        site_packages = [os.path.join(pkg, "Lib", "site-packages")] + sorted(
            glob.glob(os.path.join(pkg, "lib", "python*", "site-packages")))
        for env in (self.buildenv_info, self.runenv_info):
            for site in site_packages:
                env.prepend_path("PYTHONPATH", site)
            env.prepend_path("PATH", os.path.join(pkg, "bin"))
            env.prepend_path("PATH", os.path.join(pkg, "Scripts"))
