#!/usr/bin/env python3
"""Generate one Conan recipe per ROS package from rosdistro (proof of concept).

Same idea as RoboStack's vinca, emitting conan-center-index layout instead of conda
recipes: read the pinned rosdistro, walk the dependency closure of a seed package,
and write `<out>/recipes/<pkg>/{config.yml,all/{conanfile.py,conandata.yml}}`.

Sources are the per-package tarballs of the ros2-gbp release repositories, the same
ones bloom/rosdistro point at, so each Conan package maps 1:1 to a released ROS
package instead of the whole distro being one monolithic recipe.

Everything distro-specific lives in `<repo>/<distro>/`. Canonical generation
(`--lock`) writes `recipes/` there; `--seed` writes a partial index under
`<distro>/.generated/` so a local experiment does not rewrite the committed tree:

    python tools/gen_ros_recipes.py --distro kilted --lock
    conan remote add ros-kilted ./kilted --type=local-recipes-index
    conan install --requires=ament_cmake/2.7.5@ros-kilted --build=missing

Requires PyYAML:  pip install pyyaml
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import shutil
import sys
import tarfile
from dataclasses import dataclass
from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover - same guard as rosdistro_index
    raise SystemExit("PyYAML is required: pip install pyyaml") from exc

TOOLS_DIR = Path(__file__).resolve().parent
REPO_ROOT = TOOLS_DIR.parent
sys.path.insert(0, str(TOOLS_DIR))

import ros_pkgxml  # noqa: E402
import rosdistro_index as rdi  # noqa: E402

GENERATED_HEADER = (
    "# Generated by tools/gen_ros_recipes.py from rosdistro. Do not edit by hand."
)
GBP_ARCHIVE = "{repo}/archive/refs/tags/{tag}.tar.gz"


class GeneratorError(Exception):
    """User-facing generator error."""


@dataclass
class PipPackage:
    """A PyPI distribution generated as a Conan package."""

    ref: str
    pure: bool = True

    @classmethod
    def parse(cls, value) -> "PipPackage":
        if isinstance(value, str):
            return cls(ref=value)
        return cls(ref=value["ref"], pure=bool(value.get("pure", True)))


@dataclass
class RosDepMap:
    requires: dict
    tool_requires: dict
    pip: dict
    pip_packages: dict
    ignore: dict
    implicit: dict
    skip_packages: dict
    extra_requires: dict
    cmake_variables: dict
    cmake_target_names: dict
    dep_options: dict
    propagate_python_version: list
    patches: dict
    path: Path

    @classmethod
    def load(cls, path: Path) -> "RosDepMap":
        if not path.is_file():
            raise GeneratorError(f"No rosdep map at {path}")
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        return cls(
            path=path,
            requires=data.get("requires") or {},
            tool_requires=data.get("tool_requires") or {},
            pip=data.get("pip") or {},
            pip_packages={
                key: PipPackage.parse(value)
                for key, value in (data.get("pip_packages") or {}).items()
            },
            ignore=data.get("ignore") or {},
            implicit=data.get("implicit") or {},
            skip_packages=data.get("skip_packages") or {},
            extra_requires=data.get("extra_requires") or {},
            cmake_variables=data.get("cmake_variables") or {},
            cmake_target_names=data.get("cmake_target_names") or {},
            dep_options=data.get("dep_options") or {},
            propagate_python_version=data.get("propagate_python_version") or [],
            patches=data.get("patches") or {},
        )

    def resolve(self, key: str) -> tuple[str, str] | None:
        """Return (section, value) or None when the key is not mapped."""
        for section in ("requires", "tool_requires", "pip", "pip_packages", "ignore"):
            table = getattr(self, section)
            if key in table:
                return section, table[key]
        return None


def _archive_url(entry: dict, package: str) -> str:
    repo = entry["repo"]
    if repo.endswith(".git"):
        repo = repo[:-4]
    tag = entry["tag"].format(package=package, version=entry["version"])
    return GBP_ARCHIVE.format(repo=repo, tag=tag)


def _write(path: Path, text: str) -> None:
    """Write generated text with LF endings on every platform.

    `Path.write_text` translates "\\n" to os.linesep, so the same generator run would
    produce CRLF files on Windows and LF files elsewhere. The committed index has to be
    byte-identical whoever regenerates it, or the drift check fails on the other OS.
    """
    path.write_text(text, encoding="utf-8", newline="\n")


def _fetch_archive(url: str, cache_dir: Path) -> tuple[str, bytes]:
    """Download once, keep it around: the sha256 needs the bytes anyway."""
    cache_dir.mkdir(parents=True, exist_ok=True)
    cached = cache_dir / hashlib.sha256(url.encode()).hexdigest()[:16]
    if cached.is_file():
        data = cached.read_bytes()
    else:
        print(f"  fetching {url}")
        data = rdi.download(url)
        cached.write_bytes(data)
    return hashlib.sha256(data).hexdigest(), data


def _manifest_from_archive(data: bytes, package: str, work_dir: Path):
    """Parse the package.xml shipped in the release tarball, not the rosdistro cache.

    The cache tracks the latest sync; the tarball is what actually gets built.

    Returns the manifest and a `read_text(name)` over the root files that
    `ros_pkgxml` introspects, so the detectors work off the released sources.
    """
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tar:
        names = tar.getnames()
        member = next((n for n in names if n.count("/") == 1 and n.endswith("/package.xml")), None)
        if member is None:
            raise GeneratorError(f"{package}: no package.xml at the root of the release tarball")
        payload = tar.extractfile(member).read()
        root = member.split("/", 1)[0] + "/"
        siblings = {n[len(root):] for n in names if n.startswith(root)}
        root_files = {
            name: tar.extractfile(root + name).read().decode("utf-8", errors="replace")
            for name in ros_pkgxml.INTROSPECTED_FILES
            if name in siblings
        }

    work_dir.mkdir(parents=True, exist_ok=True)
    xml_path = work_dir / "package.xml"
    xml_path.write_bytes(payload)
    manifest = ros_pkgxml.parse_package_manifest(xml_path)
    if not manifest.build_type:
        # No <export><build_type>: infer from what the tarball actually ships.
        if "CMakeLists.txt" in siblings:
            manifest.build_type = ros_pkgxml.CMAKE
        elif "setup.py" in siblings or "setup.cfg" in siblings:
            manifest.build_type = (
                ros_pkgxml.AMENT_PYTHON if "resource" in siblings else ros_pkgxml.PYTHON
            )
    return manifest, lambda name: root_files.get(name, "")


def _write_recipe(out_root: Path, spec, source: dict | None = None) -> None:
    recipe_dir = out_root / "recipes" / spec.name
    if recipe_dir.exists():
        shutil.rmtree(recipe_dir)
    (recipe_dir / "all").mkdir(parents=True, exist_ok=True)
    _write(
        recipe_dir / "config.yml",
        yaml.safe_dump({"versions": {spec.version: {"folder": "all"}}}, sort_keys=False),
    )
    conandata = {}
    if source:
        conandata["sources"] = {spec.version: source}
    if spec.file_patches:
        conandata["patches"] = {
            spec.version: [
                {"patch_file": p["patch_file"], "patch_description": p.get("patch_description", "")}
                for p in spec.file_patches
            ]
        }
        patches_dest = recipe_dir / "all" / "patches"
        patches_dest.mkdir(parents=True, exist_ok=True)
        for patch in spec.file_patches:
            src = Path(patch["src"])
            shutil.copy2(src, patches_dest / Path(patch["patch_file"]).name)
    if conandata:
        _write(recipe_dir / "all" / "conandata.yml", yaml.safe_dump(conandata, sort_keys=False))
    _write(recipe_dir / "all" / "conanfile.py", ros_pkgxml.render_recipe(spec))


def _extra_packages(config: rdi.DistroConfig) -> list[dict]:
    """Hand-written recipes under <distro>/extra/, copied into the index as-is."""
    extra = config.extra_dir
    if not extra.is_dir():
        return []
    packages = []
    for recipe in sorted(p for p in extra.iterdir() if p.is_dir()):
        config_yml = recipe / "config.yml"
        if not config_yml.is_file():
            raise GeneratorError(f"{recipe} is missing config.yml")
        versions = (yaml.safe_load(config_yml.read_text(encoding="utf-8")) or {}).get("versions") or {}
        if len(versions) != 1:
            raise GeneratorError(f"{recipe}: extra recipes must declare exactly one version")
        version = next(iter(versions))
        folder = versions[version].get("folder", "all")
        conanfile = recipe / folder / "conanfile.py"
        if not conanfile.is_file():
            raise GeneratorError(f"{recipe}: missing {folder}/conanfile.py")
        packages.append(
            {
                "name": recipe.name,
                "version": str(version),
                "build_type": "extra",
                "src": recipe,
            }
        )
    return packages


def _copy_extra_recipes(out_root: Path, extras: list[dict]) -> None:
    for package in extras:
        dest = out_root / "recipes" / package["name"]
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(package["src"], dest)


def _prune_recipes(out_root: Path, keep: set[str]) -> None:
    recipes = out_root / "recipes"
    if not recipes.is_dir():
        return
    for pkg in recipes.iterdir():
        if pkg.is_dir() and pkg.name not in keep:
            shutil.rmtree(pkg)


def _pip_package_spec(package: PipPackage, user: str) -> "ros_pkgxml.RecipeSpec":
    name, version = package.ref.split("/", 1)
    return ros_pkgxml.RecipeSpec(
        name=name,
        version=version,
        user=user,
        license="unknown",
        build_type=ros_pkgxml.PIP,
        pip_install=f"{name}=={version}",
        header=GENERATED_HEADER,
        arch_independent=package.pure,
        python_extension=not package.pure,
    )


def _with_user(ref: str, user: str) -> str:
    return ref if "@" in ref else f"{ref}@{user}"


def _qualify_ref(ref: str, user: str, local_names: set[str]) -> str:
    """Attach the distro user when the requirement is a generated index package."""
    name = ref.split("/", 1)[0]
    if name in local_names:
        return _with_user(ref, user)
    return ref


def _dep_options(ref: str, rosdep_map: RosDepMap) -> dict | None:
    """Options a dependency needs from us, rather than from its own defaults.

    Options are graph-wide in Conan, so declaring them here rather than in a profile
    does not make conflicts go away: it turns them into an explicit resolution error
    instead of a silent override from outside. That is the point.
    """
    name = ref.split("/", 1)[0]
    options = dict(rosdep_map.dep_options.get(name) or {})
    if name in rosdep_map.propagate_python_version:
        options["python_version"] = ros_pkgxml.PYTHON_VERSION_EXPR
    return options or None


def _cmake_variable(value: str) -> str:
    """`<kind>:<package>` from the yaml -> the python expression the recipe evaluates."""
    kind, _, package = value.partition(":")
    if kind == "includedir":
        return (
            f'self.dependencies["{package}"].cpp_info.includedirs[0].replace("\\\\", "/")'
        )
    if kind == "target":
        return f'self.dependencies["{package}"].cpp_info.get_property("cmake_target_name")'
    if kind == "literal":
        return repr(package)
    raise GeneratorError(
        f"Unknown cmake_variables form '{value}'. Use includedir:, target: or literal:."
    )


def _verify_patches(data: bytes, package: str, patches: list) -> None:
    """A patch that no longer matches is a silent no-op at build time. Fail here instead."""
    if not patches:
        return
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tar:
        names = tar.getnames()
        root = next((n for n in names if n.count("/") == 1), "").split("/", 1)[0] + "/"
        for patch in patches:
            member = root + patch["file"]
            if member not in names:
                raise GeneratorError(
                    f"{package}: patch targets {patch['file']}, absent from the release tarball"
                )
            content = tar.extractfile(member).read().decode("utf-8", errors="replace")
            if patch["search"] not in content:
                raise GeneratorError(
                    f"{package}: patch for {patch['file']} no longer matches upstream.\n"
                    f"  looked for: {patch['search'].splitlines()[0]}...\n"
                    f"  update the `patches` entry in the rosdep map, or drop it if upstream fixed it."
                )


def _reachable_deps(package: str, dep_names: dict, cache: dict) -> set:
    """Every dependency name reachable from a package, not just its direct ones.

    A target rename has to be applied by whoever generates the CMakeDeps files that
    declare the target, and that is not only the package that links the library:
    mcap_vendor bakes `LZ4::lz4;zstd::zstd` into its exported config, so every consumer of
    mcap_vendor has to resolve those names too. Walking the requirements is what keeps the
    rename off the 200 recipes that never see lz4.
    """
    if package in cache:
        return cache[package]
    cache[package] = set()  # visited marker, so a cycle cannot recurse forever
    reachable = set()
    for dep in dep_names.get(package, ()):
        reachable.add(dep)
        if dep in dep_names:
            reachable |= _reachable_deps(dep, dep_names, cache)
    cache[package] = reachable
    return reachable


@dataclass
class Distribution:
    """The pinned rosdistro, downloaded once and walked many times."""

    index: dict
    xmls: dict

    @classmethod
    def fetch(cls, config: rdi.DistroConfig) -> "Distribution":
        print(f"Downloading {config.rosdistro_url}")
        index = rdi.distribution_index(rdi.download(config.rosdistro_url), config.name)
        print(f"Downloading {config.cache_url}")
        xmls = rdi.package_xml_map(rdi.download(config.cache_url))
        return cls(index=index, xmls=xmls)

    def closure(self, seeds: list, skip: dict) -> list:
        reached = rdi.closure(seeds, self.xmls, skip=skip)
        return sorted(p for p in reached if p in self.xmls)


def generate(
    seeds: list[str],
    config: rdi.DistroConfig,
    out_root: Path,
    cache_dir: Path,
    rosdep_map: RosDepMap,
    dry_run: bool = False,
    distribution: "Distribution | None" = None,
    prune: bool = False,
) -> dict:
    distro = config.name
    distribution = distribution or Distribution.fetch(config)
    index, xmls = distribution.index, distribution.xmls
    packages = distribution.closure(seeds, rosdep_map.skip_packages)
    print(f"Closure of {', '.join(seeds)}: {len(packages)} ROS packages")

    user = config.conan_user
    extras = _extra_packages(config)
    extra_names = {package["name"] for package in extras}
    versions = {}
    for package in packages:
        entry = index.get(package)
        if entry is None:
            raise GeneratorError(f"{package} is not released in the pinned {distro} distribution")
        versions[package] = entry["version"].split("-", 1)[0]

    unmapped: dict[str, list[str]] = {}
    unsupported: dict[str, str] = {}
    pip_packages: dict[str, PipPackage] = {}
    # Recipes are written after the walk: what a package needs from cmake_target_names
    # depends on requirements of packages that may not have been visited yet.
    pending: dict[str, tuple] = {}
    dep_names: dict[str, set] = {}
    report_index: dict[str, dict] = {}
    for package in packages:
        entry = index[package]
        url = _archive_url(entry, package)
        sha256, data = _fetch_archive(url, cache_dir)
        manifest, read_root = _manifest_from_archive(
            data, package, cache_dir / "pkgxml" / package
        )

        if manifest.build_type not in ros_pkgxml.SUPPORTED_BUILD_TYPES:
            unsupported[package] = manifest.build_type or "(missing)"
            continue

        requires, tool_requires, pip_requires, missing = [], [], [], []
        needs_pip: list[str] = []
        for dep in sorted(manifest.deps):
            if dep == package or dep in rosdep_map.skip_packages:
                continue
            if dep in versions:
                requires.append(
                    ros_pkgxml.RecipeRequire(
                        f"{dep}/{versions[dep]}@{user}",
                        run=True,
                        transitive=manifest.build_type in ros_pkgxml.CMAKE_BUILD_TYPES,
                    )
                )
                continue
            resolved = rosdep_map.resolve(dep)
            if resolved is None:
                missing.append(dep)
                continue
            section, value = resolved
            if section == "requires":
                requires.append(
                    ros_pkgxml.RecipeRequire(
                        _qualify_ref(value, user, extra_names),
                        options=_dep_options(value, rosdep_map),
                    )
                )
            elif section == "tool_requires":
                tool_requires.append(value)
            elif section == "pip":
                pip_requires.append(value)
            elif section == "pip_packages":
                pip_packages[value.ref] = value
                needs_pip.append(value.ref)
                requires.append(
                    ros_pkgxml.RecipeRequire(
                        _with_user(value.ref, user), run=True, transitive=False
                    )
                )
        if missing:
            unmapped[package] = missing
            continue

        for ref in rosdep_map.extra_requires.get(package) or []:
            requires.append(
                ros_pkgxml.RecipeRequire(
                    _qualify_ref(ref, user, extra_names),
                    options=_dep_options(ref, rosdep_map),
                )
            )

        implicit = rosdep_map.implicit.get(manifest.build_type) or {}
        known_pip = {p.ref: p for p in rosdep_map.pip_packages.values()}
        for ref in implicit.get("requires") or []:
            if ref.split("/", 1)[0] == package:
                continue  # the package that does declare the rosdep key
            if ref in known_pip:
                pip_packages[ref] = known_pip[ref]
                needs_pip.append(ref)
            requires.append(
                ros_pkgxml.RecipeRequire(_with_user(ref, user), run=True, transitive=False)
            )
        tool_requires += implicit.get("tool_requires") or []
        pip_requires += implicit.get("pip") or []
        requires = list({r.ref: r for r in requires}.values())
        tool_requires = sorted(set(tool_requires))
        pip_requires = sorted(set(pip_requires))

        arch_independent = ros_pkgxml.is_arch_independent(manifest.build_type, read_root)
        python_extension = ros_pkgxml.embeds_python_extension(manifest.build_type, read_root)
        vendored_prefix = ros_pkgxml.installs_vendored_prefix(manifest.build_type, read_root)
        pkg_config = ros_pkgxml.looks_up_deps_with_pkg_config(manifest.build_type, read_root)
        conan_version = versions[package]
        if manifest.version != conan_version:
            print(
                f"  WARN {package}: package.xml says {manifest.version}, "
                f"rosdistro says {conan_version}; using rosdistro"
            )
        spec = ros_pkgxml.RecipeSpec(
            name=package,
            version=conan_version,
            user=user,
            license=manifest.license,
            build_type=manifest.build_type,
            requires=requires,
            tool_requires=tool_requires,
            pip_requires=pip_requires,
            from_source=True,
            header=GENERATED_HEADER,
            arch_independent=arch_independent,
            python_extension=python_extension,
            vendored_prefix=vendored_prefix,
            pkg_config=pkg_config,
            cmake_variables={
                name: _cmake_variable(value)
                for name, value in (rosdep_map.cmake_variables.get(package) or {}).items()
            },
            # cmake_target_names needs the whole graph, so it is filled in below.
            python_version_deps=[r.ref for r in requires if r.options],
            patches=rosdep_map.patches.get(package) or [],
        )
        _verify_patches(data, package, spec.patches)
        pending[package] = (spec, {"url": url, "sha256": sha256})
        dep_names[package] = {r.ref.split("/", 1)[0] for r in requires}
        report_index[package] = {
            "name": package,
            "version": conan_version,
            "build_type": manifest.build_type,
            "arch_independent": arch_independent,
            "python_extension": python_extension,
            "vendored_prefix": vendored_prefix,
            "pkg_config": pkg_config,
            "ros_requires": len([r for r in requires if r.ref.endswith(f"@{user}")]),
            "tool_requires": tool_requires,
            "pip_requires": pip_requires,
            "pip_packages": sorted(set(needs_pip)),
        }

    if unmapped:
        listed = "\n".join(f"  {p}: {', '.join(d)}" for p, d in sorted(unmapped.items()))
        raise GeneratorError(
            "These keys in distro.yaml are not mapped "
            "(requires / tool_requires / pip / pip_packages / ignore):\n"
            f"{listed}\n"
            "Add them (requires / tool_requires / pip / pip_packages / ignore) and re-run."
        )
    if unsupported:
        listed = ", ".join(f"{p} ({b})" for p, b in sorted(unsupported.items()))
        raise GeneratorError(f"Unsupported build_type: {listed}")

    reach_cache: dict[str, set] = {}
    for package, (spec, source) in pending.items():
        if spec.build_type in ros_pkgxml.CMAKE_BUILD_TYPES:
            reachable = _reachable_deps(package, dep_names, reach_cache)
            spec.cmake_target_names = {
                dep: target
                for dep, target in rosdep_map.cmake_target_names.items()
                if dep in reachable
            }
        report_index[package]["target_renames"] = sorted(spec.cmake_target_names)
        if not dry_run:
            _write_recipe(out_root, spec, source=source)

    for ref in sorted(pip_packages):
        spec = _pip_package_spec(pip_packages[ref], user)
        if not dry_run:
            _write_recipe(out_root, spec)

    extra = [{"name": p["name"], "version": p["version"], "build_type": p["build_type"]} for p in extras]
    if not dry_run:
        _copy_extra_recipes(out_root, extras)
    if prune and not dry_run:
        keep = set(pending)
        keep.update(ref.split("/", 1)[0] for ref in pip_packages)
        keep.update(p["name"] for p in extra)
        _prune_recipes(out_root, keep)

    report_packages = list(report_index.values())
    return {
        "distro": distro,
        "rosdistro_tag": config.rosdistro_tag,
        "seeds": seeds,
        "user": user,
        "packages": report_packages,
        "extra_packages": extra,
        "build_types": _count(p["build_type"] for p in report_packages),
        "arch_independent": sorted(p["name"] for p in report_packages if p["arch_independent"]),
        "python_extension": sorted(p["name"] for p in report_packages if p["python_extension"]),
        "vendored_prefix": sorted(p["name"] for p in report_packages if p["vendored_prefix"]),
        "pkg_config": sorted(p["name"] for p in report_packages if p["pkg_config"]),
        "target_renames": sorted(p["name"] for p in report_packages if p.get("target_renames")),
        "pip_packages": sorted(pip_packages),
        "skipped_packages": rosdep_map.skip_packages,
        "pip_requires": sorted({p for e in report_packages for p in e["pip_requires"]}),
        "tool_requires": sorted({t for e in report_packages for t in e["tool_requires"]}),
    }


LOCK_HEADER = """\
# Coverage manifest. Generated by `tools/gen_ros_recipes.py --distro {distro} --lock`.
# Do not edit by hand: edit distro.yaml and regenerate.
#
# One line per package the granular recipes cover, with the version the pinned rosdistro
# releases and how it is built. Adding a root package shows up here as every transitive
# dependency it pulls in, which is what makes the PR reviewable.
"""


def render_lock(config: rdi.DistroConfig, report: dict) -> str:
    def entry(name: str, version: str, build_type: str) -> str:
        return f"  {name}: {{version: {version}, build_type: {build_type}}}"

    lines = [
        LOCK_HEADER.format(distro=config.name),
        f"distro: {config.name}",
        f"rosdistro_tag: {config.rosdistro_tag}",
        f"conan_user: {config.conan_user}",
        f"requested_packages: [{', '.join(config.packages)}]",
        "",
        "packages:",
    ]
    lines += [
        entry(p["name"], p["version"], p["build_type"])
        for p in sorted(report["packages"], key=lambda p: p["name"])
    ]

    lines += [
        "",
        "# PyPI distributions wrapped as Conan packages, so the build does not reach the",
        "# network for them and their version is pinned like everything else.",
        "pip_packages:",
    ]
    lines += [
        entry(*ref.split("/", 1), ros_pkgxml.PIP)
        for ref in sorted(report["pip_packages"])
    ]
    extra = report.get("extra_packages") or []
    if extra:
        lines += [
            "",
            "# Hand-written recipes from extra/, not rosdistro.",
            "extra_packages:",
        ]
        lines += [
            entry(e["name"], e["version"], e["build_type"])
            for e in extra
        ]
    return "\n".join(lines) + "\n"


def lock_entries(text: str) -> dict:
    """The `name: {...}` lines of a lock, without caring how it is laid out."""
    doc = yaml.safe_load(text) or {}
    return {
        **(doc.get("packages") or {}),
        **(doc.get("pip_packages") or {}),
        **(doc.get("source_packages") or {}),
        **(doc.get("extra_packages") or {}),
    }


def _report_lock_drift(config: rdi.DistroConfig, lock: str) -> None:
    if not config.lock_path.is_file():
        raise SystemExit(
            f"ERROR: {config.lock_path} does not exist. "
            f"Run: python tools/gen_ros_recipes.py --distro {config.name} --lock"
        )
    committed = config.lock_path.read_text(encoding="utf-8")
    if committed == lock:
        print(f"\n{config.lock_path.name} is up to date")
        return

    old, new = lock_entries(committed), lock_entries(lock)
    added = sorted(set(new) - set(old))
    removed = sorted(set(old) - set(new))
    changed = sorted(k for k in set(old) & set(new) if old[k] != new[k])
    for label, names in (("+", added), ("-", removed), ("~", changed)):
        for name in names:
            print(f"  {label} {name}")
    raise SystemExit(
        f"\nERROR: {config.lock_path} is out of date "
        f"({len(added)} added, {len(removed)} removed, {len(changed)} changed).\n"
        f"Run: python tools/gen_ros_recipes.py --distro {config.name} --lock"
    )


def _count(values) -> dict:
    counts: dict[str, int] = {}
    for value in values:
        counts[value] = counts.get(value, 0) + 1
    return counts


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--distro", default="kilted")
    parser.add_argument("--seed", nargs="+", default=None, help="Seed package(s)")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=None,
        help="local-recipes-index root (default: <repo>/<distro>/)",
    )
    parser.add_argument("--download-cache", type=Path, default=None)
    parser.add_argument("--dry-run", action="store_true", help="Report only, write nothing")
    parser.add_argument(
        "--lock",
        action="store_true",
        help="Generate the configured package closure and rewrite packages.lock.yaml plus recipes/",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Like --lock but writes nothing: fails if the committed lock is out of date",
    )
    args = parser.parse_args()

    locking = args.lock or args.check
    if locking and args.seed:
        raise SystemExit("ERROR: --lock and --check use distro.yaml, so they take no seeds")
    if not locking and not args.seed:
        raise SystemExit("ERROR: use --lock, --check, or --seed for a partial generation")

    try:
        config = rdi.DistroConfig.load(args.distro)
        seeds = config.packages if locking else args.seed
    except rdi.DistroError as exc:
        raise SystemExit(f"ERROR: {exc}") from exc

    args.output = args.output or (
        config.index_root if locking else config.index_root / ".generated"
    )
    cache_dir = args.download_cache or (config.index_root / ".downloads")
    try:
        rosdep_map = RosDepMap.load(config.rosdep_map_path)
        distribution = Distribution.fetch(config)
        report = generate(
            seeds=seeds,
            config=config,
            out_root=args.output,
            cache_dir=cache_dir,
            rosdep_map=rosdep_map,
            dry_run=args.dry_run or args.check,
            distribution=distribution,
            prune=bool(args.lock) and args.output.name != ".generated",
        )
        if locking:
            lock = render_lock(config, report)
    except GeneratorError as exc:
        raise SystemExit(f"ERROR: {exc}") from exc

    print()
    print(f"packages:      {len(report['packages'])}")
    print(f"build types:   {report['build_types']}")
    print(
        f"arch indep.:   {len(report['arch_independent'])} of {len(report['packages'])} "
        "(one binary per OS instead of one per compiler/build_type/arch)"
    )
    print(
        f"py extension:  {len(report['python_extension'])} of {len(report['packages'])} "
        "(python_version in the package_id)"
    )
    print(f"vendored:      {report['vendored_prefix'] or '(none)'} (publish opt/<name>)")
    print(f"pkg-config:    {report['pkg_config'] or '(none)'} (also generate .pc files)")
    print(f"target renames:{report['target_renames'] or '(none)'}")
    print(f"extra pkgs:    {[p['name'] for p in report.get('extra_packages') or []] or '(none)'}")
    print(f"pip packages:  {report['pip_packages'] or '(none)'}")
    print(f"tool_requires: {report['tool_requires'] or '(none)'}")
    print(f"pip requires:  {report['pip_requires'] or '(none)'}")

    if args.check:
        return _report_lock_drift(config, lock)
    if args.lock:
        _write(config.lock_path, lock)
        print(f"\nWrote {config.lock_path}")
    if args.dry_run:
        print("dry-run: no recipes written")
        return
    report_path = args.output / ".report.json"
    _write(report_path, json.dumps(report, indent=2) + "\n")
    print(f"\nWrote {len(report['packages'])} recipes to {args.output / 'recipes'}")
    print(f"Wrote {report_path}")


if __name__ == "__main__":
    main()
