"""Parse ROS package.xml files and render Conan recipes for the rosdistro generator."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from xml.etree import ElementTree as ET

DEPEND_TAGS = {
    "depend",
    "build_depend",
    "build_export_depend",
    "exec_depend",
    "buildtool_depend",
    "buildtool_export_depend",
}

GENERATED_HEADER_PY = "# Generated by tools/gen_ros_recipes.py. Do not edit by hand."
AMENT_CMAKE = "ament_cmake"
AMENT_PYTHON = "ament_python"
CMAKE = "cmake"
PYTHON = "python"
BUILD_TYPE_ALIASES = {
    "ament_cmake_auto": AMENT_CMAKE,
    "ament_cmake_python": AMENT_CMAKE,
    "ament_cmake_ros": AMENT_CMAKE,
}
CMAKE_BUILD_TYPES = (AMENT_CMAKE, CMAKE)
PYTHON_BUILD_TYPES = (AMENT_PYTHON, PYTHON)
PIP = "pip"
EXTERNAL_CMAKE = "external_cmake"
SUPPORTED_BUILD_TYPES = CMAKE_BUILD_TYPES + PYTHON_BUILD_TYPES


class RosConsumerError(Exception):
    """Malformed package.xml or unsupported build type."""


def _local_tag(tag: str) -> str:
    return tag.split("}", 1)[-1]


def _text(node: ET.Element | None) -> str:
    if node is None or node.text is None:
        return ""
    return node.text.strip()


@dataclass
class PackageManifest:
    name: str
    version: str
    license: str
    build_type: str
    deps: set[str]
    path: Path


def _infer_build_type(package_dir: Path, deps: set[str]) -> str:
    """<export><build_type> is optional; fall back to the buildtool deps and the layout."""
    if AMENT_CMAKE in deps:
        return AMENT_CMAKE
    if (package_dir / "CMakeLists.txt").is_file():
        return CMAKE
    if (package_dir / "setup.py").is_file() or (package_dir / "setup.cfg").is_file():
        return AMENT_PYTHON if (package_dir / "resource").is_dir() else PYTHON
    return ""


_CMAKE_COMMENT_RE = re.compile(r"#[^\n]*")
_CMAKE_PROJECT_RE = re.compile(r"^[ \t]*project[ \t]*\(([^)]*)\)", re.IGNORECASE | re.MULTILINE)
_CMAKE_ENABLE_LANGUAGE_RE = re.compile(r"\benable_language[ \t]*\(", re.IGNORECASE)
# setuptools only produces machine code through an extension module.
_PY_EXTENSION_RE = re.compile(r"\bext_modules\b|\bExtension[ \t]*\(|\bbuild_ext\b")
# CMake calls that end up installing a .pyd/.so tagged for one CPython minor version.
# rosidl_generate_interfaces is the common one: it runs rosidl_generator_py, which builds
# an extension module for every interface package.
_CMAKE_PY_EXTENSION_RE = re.compile(
    r"\brosidl_generate_interfaces[ \t]*\(|\bpybind11_add_module[ \t]*\(|"
    r"\bpython\d*_add_library[ \t]*\(",
    re.IGNORECASE,
)
# ament_vendor() builds a bundled library and installs it under opt/<name>.
_AMENT_VENDOR_RE = re.compile(r"\bament_vendor[ \t]*\(", re.IGNORECASE)
# Packages that look for a dependency through pkg-config instead of find_package().
_PKG_CONFIG_RE = re.compile(
    r"\bpkg_check_modules[ \t]*\(|\bpkg_search_module[ \t]*\(|\bpkg_get_variable[ \t]*\(",
    re.IGNORECASE,
)

# Files a detector may look at, so callers reading from an archive know what to extract.
INTROSPECTED_FILES = ("CMakeLists.txt", "setup.py", "setup.cfg", "pyproject.toml")


def cmake_declares_no_languages(text: str) -> bool:
    """True for `project(<name> NONE)`, which tells CMake to load no compiler at all.

    This is not a guess about what the package installs: after a NONE project CMake
    refuses to compile anything unless the project calls enable_language().
    """
    body = _CMAKE_COMMENT_RE.sub("", text)
    match = _CMAKE_PROJECT_RE.search(body)
    if match is None:
        return False
    arguments = match.group(1).split()
    if not arguments or arguments[-1].upper() != "NONE":
        return False
    return not _CMAKE_ENABLE_LANGUAGE_RE.search(body)


def package_file_reader(package_dir: Path):
    """A `read_text(name)` over a working copy, for the detectors below."""

    def read_text(name: str) -> str:
        path = package_dir / name
        if not path.is_file():
            return ""
        return path.read_text(encoding="utf-8", errors="replace")

    return read_text


def is_arch_independent(build_type: str, read_text) -> bool:
    """True when nothing the package installs can be machine code.

    `read_text(name)` returns the contents of a file at the package root, or "" when it
    is not there; callers read either from a working copy or from a release tarball.
    Such a package is the same binary for every compiler, build type and architecture,
    so the generated recipe drops those settings from its package_id.
    """
    if build_type in CMAKE_BUILD_TYPES:
        return cmake_declares_no_languages(read_text("CMakeLists.txt"))
    if build_type in PYTHON_BUILD_TYPES:
        return not _declares_py_extension(read_text)
    return False


def _declares_py_extension(read_text) -> bool:
    return any(
        _PY_EXTENSION_RE.search(read_text(name))
        for name in ("setup.py", "setup.cfg", "pyproject.toml")
    )


def installs_vendored_prefix(build_type: str, read_text) -> bool:
    """True when the package calls ament_vendor(), which installs under `opt/<name>`.

    That prefix is outside the layout Conan assumes, so the recipe has to publish it. Only
    the packages that call the macro need those lines: emitting them everywhere would put
    a dead branch in every recipe and, worse, tie every recipe revision to a fix that
    concerns four of them.
    """
    return build_type in CMAKE_BUILD_TYPES and bool(
        _AMENT_VENDOR_RE.search(read_text("CMakeLists.txt"))
    )


def looks_up_deps_with_pkg_config(build_type: str, read_text) -> bool:
    """True when the package resolves a dependency through pkg-config.

    CMakeDeps writes config files, which pkg_check_modules() never reads: theora_image
    transport asks pkg-config for ogg and theora and fails to configure even though both
    are in the graph. The recipe has to add PkgConfigDeps for those, and only for those,
    since it also decides where PKG_CONFIG_PATH points.
    """
    return build_type in CMAKE_BUILD_TYPES and bool(
        _PKG_CONFIG_RE.search(read_text("CMakeLists.txt"))
    )


def embeds_python_extension(build_type: str, read_text) -> bool:
    """True when the package installs an extension module.

    Such a file is named for the interpreter that built it, `_rclpy_pybind11.cp314-win_amd64.pyd`,
    and is unusable under any other CPython minor version. Nothing else in a Conan graph
    records the interpreter, so the generated recipe has to put it in its package_id.
    """
    if build_type in CMAKE_BUILD_TYPES:
        return bool(_CMAKE_PY_EXTENSION_RE.search(read_text("CMakeLists.txt")))
    if build_type in PYTHON_BUILD_TYPES:
        return _declares_py_extension(read_text)
    return False


def parse_package_manifest(path: Path) -> PackageManifest:
    root = ET.parse(path).getroot()
    name = ""
    version = ""
    license_name = ""
    build_type = ""
    deps: set[str] = set()
    for child in list(root):
        tag = _local_tag(child.tag)
        if tag == "name" and not name:
            name = _text(child)
        elif tag == "version" and not version:
            version = _text(child)
        elif tag == "license" and not license_name:
            license_name = _text(child)
        elif tag in DEPEND_TAGS:
            dep = _text(child)
            if dep:
                deps.add(dep)
        elif tag == "export":
            for sub in list(child):
                if _local_tag(sub.tag) == "build_type" and not build_type:
                    build_type = _text(sub)
    if not name:
        raise RosConsumerError(f"{path}: package.xml has no <name>")
    if not version:
        raise RosConsumerError(f"{path}: package.xml has no <version>")
    build_type = BUILD_TYPE_ALIASES.get(build_type, build_type)
    if not build_type:
        build_type = _infer_build_type(path.parent, deps)
    return PackageManifest(
        name=name,
        version=version,
        license=license_name or "unknown",
        build_type=build_type,
        deps=deps,
        path=path,
    )



CMAKE_EXPORTS = (
    "CMakeLists.txt",
    "cmake/*",
    "package.xml",
    "src/*",
    "include/*",
    "msg/*",
    "srv/*",
    "action/*",
    "launch/*",
    "config/*",
    "resource/*",
)
PYTHON_EXPORTS = (
    "package.xml",
    "setup.py",
    "setup.cfg",
    "pyproject.toml",
    "launch/*",
    "config/*",
    "resource/*",
    "scripts/*",
)

# Site-packages layout differs between Windows and the rest, same as in the ros-kilted recipe.
SITE_PACKAGES_SNIPPET = '''        site_packages = [os.path.join(pkg, "Lib", "site-packages")] + sorted(
            glob.glob(os.path.join(pkg, "lib", "python*", "site-packages")))'''


def _exports_block(patterns) -> str:
    return "\n".join(f'        "{p}",' for p in patterns)


class RawOption(str):
    """An option value written into the recipe as an expression, not a string literal."""


def _option_value(value) -> str:
    return str(value) if isinstance(value, RawOption) else f'"{value}"'


# The interpreter the recipe runs under, for dependencies that pick theirs by option.
PYTHON_VERSION_EXPR = RawOption('f"{sys.version_info.major}.{sys.version_info.minor}"')


@dataclass
class RecipeRequire:
    """One `self.requires()` line of a generated recipe."""

    ref: str
    options: dict | None = None
    run: bool = False
    transitive: bool = True


@dataclass
class RecipeSpec:
    """Inputs for the generated Conan recipe templates."""

    name: str
    version: str
    user: str
    license: str
    build_type: str
    requires: list = field(default_factory=list)
    tool_requires: list = field(default_factory=list)
    pip_requires: list = field(default_factory=list)
    from_source: bool = False
    header: str = GENERATED_HEADER_PY
    pip_install: str = ""  # PyPI requirement, only with build_type PIP
    arch_independent: bool = False
    python_extension: bool = False
    # The package calls ament_vendor(), so it may install under opt/<name>.
    vendored_prefix: bool = False
    # The package calls pkg_check_modules(), which needs .pc files, not CMake configs.
    pkg_config: bool = False
    # CMake cache variable -> python expression, emitted verbatim into generate().
    cmake_variables: dict = field(default_factory=dict)
    # Dependency name -> the CMake target name this package expects it to have.
    cmake_target_names: dict = field(default_factory=dict)
    # Dependencies whose own python_version option has to track this graph's interpreter.
    python_version_deps: list = field(default_factory=list)
    # Edits applied to the downloaded sources, as {"file", "search", "replace"} mappings.
    patches: list = field(default_factory=list)
    # Unified-diff patches listed in conandata.yml and applied with apply_conandata_patches.
    file_patches: list = field(default_factory=list)
    # Configure CMake in this subdirectory of the source tree, if set.
    build_folder: str = ""
    # Copy this path (relative to the source tree) into licenses/.
    license_file: str = ""
    # Library recipe: option shared, Windows forced static.
    shared_option: bool = False
    # Create a PyEnv for Python3_EXECUTABLE (compiled Python extensions).
    pyenv: bool = False
    # package_info extras for non-ament CMake libraries.
    cmake_file_name: str = ""
    cmake_target_name: str = ""
    libs: list = field(default_factory=list)
    cpp_requires: list = field(default_factory=list)
    pythonpath: bool = False



def _requirements_block(requires: list) -> str:
    """The whole `requirements()` method, or nothing when there is no dependency."""
    if not requires:
        return ""
    return f"\n    def requirements(self):\n{_requires_block(requires)}\n"


def _requires_block(requires: list) -> str:
    lines = []
    for req in requires:
        args = [f'"{req.ref}"']
        if req.transitive:
            args += ["transitive_headers=True", "transitive_libs=True"]
        if req.run:
            args.append("run=True")
        if req.options:
            opts = ", ".join(f'"{k}": {_option_value(v)}' for k, v in req.options.items())
            args.append("options={" + opts + "}")
        body = "".join(f"            {a},\n" for a in args)
        lines.append(f"        self.requires(\n{body}        )")
    return "\n".join(lines)


def _package_id_block(spec: RecipeSpec) -> str:
    """Drop from the package_id the settings the package provably cannot depend on.

    `os` always stays: the install layout (Scripts vs bin, site-packages) and the
    environment hooks differ per platform even when nothing is compiled.
    """
    if not spec.arch_independent:
        return ""
    if spec.build_type in CMAKE_BUILD_TYPES:
        reason = "project(... NONE): CMake loads no compiler, this installs macros only."
        settings = ("compiler", "build_type", "arch")
    else:
        reason = "Pure python, no extension module: one binary per platform is enough."
        settings = ("arch",)
    body = "\n".join(f"        del self.info.settings.{s}" for s in settings)
    return f"\n    def package_id(self):\n        # {reason}\n{body}\n"


def _python_version_block(spec: RecipeSpec) -> str:
    """Put the CPython minor version in the package_id of packages that install a .pyd/.so.

    Only those: a pure python package runs on any CPython 3, but an extension module is
    named for the interpreter that built it and fails to import under another one.

    The default is evaluated when Conan loads the recipe, so it follows the interpreter
    Conan itself runs, which is also the one the templates use. Pointing them elsewhere
    with `-c user.ros2:python=<path>` does not update it, so that case has to pass
    `-o <pkg>/*:python_version=<x.y>` as well.
    """
    if not spec.python_extension:
        return ""
    return (
        '\n    options = {"python_version": ["ANY"]}\n'
        "    default_options = {\n"
        '        "python_version": f"{sys.version_info.major}.{sys.version_info.minor}",\n'
        "    }\n"
    )


def _cmake_deps_block(spec: RecipeSpec) -> str:
    """CMakeDeps, renaming the targets of dependencies that ROS looks up by another name.

    A vendor package installs its own `Find<X>.cmake` declaring, say, `LZ4::lz4`. Once the
    library comes from ConanCenter instead, CMakeDeps writes the files that get found first
    and they declare `lz4::lz4`, so the consumer's target_link_libraries breaks.
    """
    if not spec.cmake_target_names:
        lines = ["        CMakeDeps(self).generate()"]
    else:
        lines = ["        deps = CMakeDeps(self)"]
        lines += [
            f'        deps.set_property("{dep}", "cmake_target_name", "{target}")'
            for dep, target in spec.cmake_target_names.items()
        ]
        lines.append("        deps.generate()")
    if spec.pkg_config:
        lines.append("        PkgConfigDeps(self).generate()")
    return "\n".join(lines) + "\n"


def _build_requirements_block(tool_requires: list) -> str:
    if not tool_requires:
        return ""
    body = "\n".join(f'        self.tool_requires("{t}")' for t in tool_requires)
    return f"\n    def build_requirements(self):\n{body}\n"


def _pyenv_block(pip_requires: list, indent: str = "        ") -> str:
    if not pip_requires:
        return ""
    pkgs = ", ".join(f'"{p}"' for p in pip_requires)
    return (
        f"{indent}pyenv = PyEnv(self)\n"
        f"{indent}pyenv.install([{pkgs}])\n"
        f"{indent}pyenv.generate()\n"
    )


def _imports_block(spec: RecipeSpec, base: list) -> str:
    imports = list(base)
    files_tools = []
    if spec.from_source:
        files_tools.append("get")
    if spec.patches:
        files_tools.append("replace_in_file")
    if spec.file_patches:
        files_tools.append("apply_conandata_patches")
    if spec.license_file:
        files_tools.append("copy")
    if files_tools:
        imports.append("from conan.tools.files import " + ", ".join(files_tools))
    if spec.pip_requires or spec.pyenv:
        imports.append("from conan.tools.system import PyEnv")
    if spec.shared_option:
        imports.append("from conan.errors import ConanInvalidConfiguration")
    return "\n".join(sorted(set(imports)))


def _source_block(spec: RecipeSpec) -> str:
    if not spec.from_source:
        return ""
    block = (
        "\n    def source(self):\n"
        '        get(self, **self.conan_data["sources"][self.version], strip_root=True)\n'
    )
    if spec.file_patches:
        block += "        apply_conandata_patches(self)\n"
    for patch in spec.patches:
        block += (
            "        replace_in_file(\n"
            "            self,\n"
            f"            os.path.join(self.source_folder, {patch['file']!r}),\n"
            f"            {patch['search']!r},\n"
            f"            {patch['replace']!r},\n"
            "        )\n"
        )
    return block


def render_recipe(spec: RecipeSpec) -> str:
    if spec.build_type == PIP:
        return _render_pip_recipe(spec)
    if spec.build_type == EXTERNAL_CMAKE:
        return _render_external_cmake_recipe(spec)
    if spec.build_type in PYTHON_BUILD_TYPES:
        return _render_python_recipe(spec)
    return _render_cmake_recipe(spec)


def _render_pip_recipe(spec: RecipeSpec) -> str:
    """A PyPI distribution as a Conan package, so PYTHONPATH reaches consumers."""
    return f'''{spec.header}
import glob
import os
import sys

from conan import ConanFile
from conan.tools.layout import basic_layout


class RosPipPackageConan(ConanFile):
    """PyPI distribution backing a rosdep key. Pure python, shared via PYTHONPATH."""

    name = "{spec.name}"
    version = "{spec.version}"
    user = "{spec.user}"
    license = {spec.license!r}
    settings = "os", "arch"
{_python_version_block(spec)}
    def layout(self):
        basic_layout(self)
{_package_id_block(spec)}
    def package(self):
        # Dependencies come along: they are pure python too and nothing else in the
        # graph provides them. Override the interpreter with -c user.ros2:python=<path>.
        python = self.conf.get("user.ros2:python", check_type=str) or sys.executable
        # --ignore-installed is not optional: --prefix does not isolate pip from the
        # interpreter running it, so pip would either skip an already satisfied
        # requirement, packaging nothing, or uninstall the ambient copy to make room
        # for a different version.
        self.run(
            f'"{{python}}" -m pip install {spec.pip_install} --no-compile '
            f'--ignore-installed --no-warn-script-location '
            f'--prefix "{{self.package_folder}}"'
        )

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        self.cpp_info.includedirs = []
        self.cpp_info.libdirs = []
        pkg = self.package_folder
{SITE_PACKAGES_SNIPPET}
        for env in (self.buildenv_info, self.runenv_info):
            for site in site_packages:
                env.prepend_path("PYTHONPATH", site)
            env.prepend_path("PATH", os.path.join(pkg, "bin"))
            env.prepend_path("PATH", os.path.join(pkg, "Scripts"))
'''


def _shared_option_block(spec: RecipeSpec) -> str:
    if not spec.shared_option:
        return ""
    extra = ""
    defaults = '        "shared": True,\n'
    if spec.python_extension:
        extra = '        "python_version": ["ANY"],\n'
        defaults += (
            '        "python_version": f"{sys.version_info.major}.{sys.version_info.minor}",\n'
        )
    return (
        "\n    options = {\n"
        '        "shared": [True, False],\n'
        f"{extra}"
        "    }\n"
        "    default_options = {\n"
        f"{defaults}"
        "    }\n"
        "\n"
        "    def config_options(self):\n"
        '        if self.settings.get_safe("os") == "Windows":\n'
        "            self.options.shared = False\n"
        "\n"
        "    def validate(self):\n"
        '        if self.options.shared and self.settings.os == "Windows":\n'
        "            raise ConanInvalidConfiguration(\n"
        f'                "{spec.name}: shared is not supported on Windows"\n'
        "            )\n"
    )


def _render_external_cmake_recipe(spec: RecipeSpec) -> str:
    """CMake library that is not a ROS package.xml (orocos_kdl and similar)."""
    imports = _imports_block(
        spec,
        [
            "from conan import ConanFile",
            "from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout",
        ],
    )
    option_block = _shared_option_block(spec)
    if spec.python_extension and not spec.shared_option:
        option_block = _python_version_block(spec)
    configure = "        cmake.configure()"
    if spec.build_folder:
        configure = (
            "        cmake.configure("
            f'build_script_folder=os.path.join(self.source_folder, "{spec.build_folder}"))'
        )
    license_copy = ""
    if spec.license_file:
        posix = spec.license_file.replace("\\", "/")
        dirname, sep, basename = posix.rpartition("/")
        src_dir = (
            f'os.path.join(self.source_folder, "{dirname}")' if dirname else "self.source_folder"
        )
        license_copy = (
            "\n        copy(\n"
            "            self,\n"
            f'            "{basename}",\n'
            f"            {src_dir},\n"
            '            os.path.join(self.package_folder, "licenses"),\n'
            "        )\n"
        )
    pyenv_block = ""
    if spec.pyenv:
        pyenv_block = (
            "        pyenv = PyEnv(self, py_version=str(self.options.python_version))\n"
            "        pyenv.generate()\n"
        )
    cache = []
    if spec.shared_option:
        cache.append('        tc.cache_variables["BUILD_SHARED_LIBS"] = self.options.shared')
    for name, expression in spec.cmake_variables.items():
        cache.append(f'        tc.cache_variables["{name}"] = {expression}')
    cache_block = "\n".join(cache) + ("\n" if cache else "")
    info_lines = []
    if spec.cmake_file_name:
        info_lines.append(
            f'        self.cpp_info.set_property("cmake_file_name", "{spec.cmake_file_name}")'
        )
    if spec.cmake_target_name:
        info_lines.append(
            f'        self.cpp_info.set_property("cmake_target_name", "{spec.cmake_target_name}")'
        )
    if spec.libs:
        info_lines.append(f"        self.cpp_info.libs = {spec.libs!r}")
    if spec.cpp_requires:
        info_lines.append(f"        self.cpp_info.requires = {spec.cpp_requires!r}")
    if spec.pythonpath:
        info_lines += [
            "        pkg = self.package_folder",
            SITE_PACKAGES_SNIPPET,
            "        def _prepend_pythonpath(path):",
            "            if os.path.isdir(path):",
            '                self.runenv_info.prepend_path("PYTHONPATH", path)',
            '                self.buildenv_info.prepend_path("PYTHONPATH", path)',
            "        for site in site_packages:",
            "            _prepend_pythonpath(site)",
        ]
    info_block = "\n".join(info_lines) if info_lines else "        pass"
    sys_import = "import sys\n" if spec.python_extension else ""
    exports = ""
    if spec.file_patches:
        exports = '    exports_sources = "conandata.yml", "patches/*"\n'
    return f'''{spec.header}
import os
{"import glob\n" if spec.pythonpath else ""}{sys_import}
{imports}


class ExternalCMakeConan(ConanFile):
    """Third-party CMake recipe template."""

    name = "{spec.name}"
    version = "{spec.version}"
    user = "{spec.user}"
    license = {spec.license!r}
    settings = "os", "compiler", "build_type", "arch"
{option_block}{exports}
    def layout(self):
        cmake_layout(self, src_folder="src")
{_requirements_block(spec.requires)}{_build_requirements_block(spec.tool_requires)}{_source_block(spec)}
    def generate(self):
{pyenv_block}        CMakeDeps(self).generate()
        tc = CMakeToolchain(self)
{cache_block}        tc.generate()

    def build(self):
        cmake = CMake(self)
{configure}
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()
{license_copy}
    def package_info(self):
{info_block}
'''


def _render_cmake_recipe(spec: RecipeSpec) -> str:
    ament = spec.build_type == AMENT_CMAKE
    # The prefix itself, so find_package() can apply its own search rules to whatever
    # layout upstream chose: urdfdom_headers installs its config in CMake/ at the root on
    # Windows and in share/ elsewhere, and enumerating those by hand only works until the
    # next package picks a third spelling. The explicit entries below stay because
    # builddirs also feeds CMAKE_MODULE_PATH, which is not prefix-relative: a Find<X>.cmake
    # shipped in share/<name>/cmake is only found if that directory is listed outright.
    builddirs = ["        self.cpp_info.builddirs.append(pkg)"]
    builddirs.append('        self.cpp_info.builddirs.append(os.path.join(pkg, "share", self.name, "cmake"))')
    if not ament:
        # Plain CMake packages usually install their config under lib/cmake/<name>.
        builddirs.append(
            '        self.cpp_info.builddirs.append(os.path.join(pkg, "lib", "cmake", self.name))'
        )
    if spec.vendored_prefix:
        # ament_vendor() installs the library it bundles under opt/<name>, outside the
        # layout Conan assumes: its config is not on the search path, so a consumer of
        # gz_cmake_vendor cannot find gz-cmake4, and its DLLs are not on PATH, so rviz2
        # exits with STATUS_DLL_NOT_FOUND before printing anything. The directory check
        # stays because a vendor package handed its library through extra_requires never
        # runs the macro and installs nothing there.
        builddirs.append('        vendored = os.path.join(pkg, "opt", self.name)')
        builddirs.append("        if os.path.isdir(vendored):")
        builddirs.append("            self.cpp_info.builddirs.append(vendored)")
        builddirs.append('            self.cpp_info.bindirs.append(os.path.join(vendored, "bin"))')
        builddirs.append('            self.cpp_info.libdirs.append(os.path.join(vendored, "lib"))')
    builddirs_block = "\n".join(builddirs)
    env_lines = ""
    if ament:
        env_lines += '            env.prepend_path("AMENT_PREFIX_PATH", pkg)\n'
    base_imports = [
        "from conan import ConanFile",
        "from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout",
    ]
    if not spec.arch_independent:
        # vcvarsall.bat rewrites PATH to several KB of VS dirs. A variant like ros_core
        # then prepends every dependency bindir; the combined PATH exceeds the Windows
        # 8191-char cap, `set PATH=` fails, and cmake.exe is gone. These packages are
        # project(NONE) and never invoke cl.exe, so the generator does not need that env.
        base_imports.append("from conan.tools.microsoft import VCVars")
    if spec.pkg_config:
        base_imports.append("from conan.tools.gnu import PkgConfigDeps")
    imports = _imports_block(spec, base_imports)
    if spec.from_source:
        layout = '        cmake_layout(self, src_folder="src")'
        sources = ""
    else:
        layout = "        cmake_layout(self)"
        sources = f"    exports_sources = (\n{_exports_block(CMAKE_EXPORTS)}\n    )\n"
    # ament macros shell out to python all through configure and build. Pin the
    # interpreter or FindPython3 takes the first one on PATH, which is not the one the
    # python dependencies of the graph were installed for.
    if spec.pip_requires:
        interpreter = ["        python = pyenv.env_exe"]
    else:
        interpreter = [
            '        python = self.conf.get("user.ros2:python", check_type=str) or sys.executable'
        ]
    interpreter += [
        # Backslashes are escapes in CMake code, and these end up in conan_toolchain.cmake.
        '        python = python.replace("\\\\", "/")',
        '        python_root = python.rsplit("/", 1)[0]',
    ]
    toolchain = interpreter + [
        "        tc = CMakeToolchain(self)",
        # test_depend is not mapped (the consumer never needs it), so the
        # find_package(ament_cmake_gtest) guarded by BUILD_TESTING must not run.
        '        tc.variables["BUILD_TESTING"] = False',
        '        tc.variables["Python3_EXECUTABLE"] = python',
        '        tc.variables["Python3_ROOT_DIR"] = python_root',
        '        tc.variables["Python_EXECUTABLE"] = python',
        '        tc.variables["Python_ROOT_DIR"] = python_root',
    ]
    toolchain += [
        f'        tc.variables["{name}"] = {expression}'
        for name, expression in spec.cmake_variables.items()
    ]
    toolchain.append("        tc.generate()")
    if not spec.arch_independent:
        toolchain.append("        VCVars(self).generate()")
    toolchain = "\n".join(toolchain)
    return f'''{spec.header}
import glob
import os
{"" if spec.pip_requires and not (spec.python_extension or spec.python_version_deps) else "import sys"}
{imports}


class RosPackageConan(ConanFile):
    """package.xml build_type: {spec.build_type}"""

    name = "{spec.name}"
    version = "{spec.version}"
    user = "{spec.user}"
    license = {spec.license!r}
    settings = "os", "compiler", "build_type", "arch"
{_python_version_block(spec)}{sources}
    def layout(self):
{layout}
{_package_id_block(spec)}{_requirements_block(spec.requires)}{_build_requirements_block(spec.tool_requires)}{_source_block(spec)}
    def generate(self):
{_pyenv_block(spec.pip_requires)}{_cmake_deps_block(spec)}
{toolchain}

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        pkg = self.package_folder
{builddirs_block}
{SITE_PACKAGES_SNIPPET}
        # Not in buildenv: CMakeToolchain already puts every dependency's builddirs in
        # CMAKE_PREFIX_PATH inside conan_toolchain.cmake, a file with no length limit,
        # and one entry per package does not fit in an environment at distro scale.
        self.runenv_info.prepend_path("CMAKE_PREFIX_PATH", pkg)
        for env in (self.buildenv_info, self.runenv_info):
{env_lines}            for site in site_packages:
                env.prepend_path("PYTHONPATH", site)
'''


def _render_python_recipe(spec: RecipeSpec) -> str:
    ament = spec.build_type == AMENT_PYTHON
    env_lines = ""
    if ament:
        env_lines += '            env.prepend_path("AMENT_PREFIX_PATH", pkg)\n'
    imports = _imports_block(
        spec,
        [
            "from conan import ConanFile",
            "from conan.tools.layout import basic_layout",
        ],
    )
    if spec.from_source:
        layout = '        basic_layout(self, src_folder="src")'
        sources = ""
    else:
        exports = PYTHON_EXPORTS + (f"{spec.name}/*",)
        layout = '        basic_layout(self, src_folder=".")'
        sources = f"    exports_sources = (\n{_exports_block(exports)}\n    )\n"
    generate = ""
    header = spec.header
    if spec.pip_requires:
        generate = f"\n    def generate(self):\n{_pyenv_block(spec.pip_requires)}"
    # With a PyEnv the interpreter is the venv one (it already has the pip requires);
    # re-instantiating in package() reuses the venv created during generate().
    interpreter = (
        "        python = PyEnv(self).env_exe"
        if spec.pip_requires
        else '        python = self.conf.get("user.ros2:python", check_type=str) or sys.executable'
    )
    sys_import = "" if spec.pip_requires and not spec.python_extension else "import sys\n"
    return f'''{header}
import glob
import os
{sys_import}
{imports}


class RosPackageConan(ConanFile):
    """package.xml build_type: {spec.build_type}"""

    name = "{spec.name}"
    version = "{spec.version}"
    user = "{spec.user}"
    license = {spec.license!r}
    settings = "os", "arch"
{_python_version_block(spec)}{sources}
    def layout(self):
{layout}
{_package_id_block(spec)}{_requirements_block(spec.requires)}{_build_requirements_block(spec.tool_requires)}{_source_block(spec)}{generate}
    def package(self):
        # setuptools does the whole build; --no-build-isolation keeps it offline, so the
        # interpreter needs setuptools. Override it with -c user.ros2:python=<path>.
        # --no-compile: .pyc are tagged for the packaging interpreter, not the ROS one.
{interpreter}
        self.run(
            f'"{{python}}" -m pip install . --no-deps --no-build-isolation --no-compile '
            f'--ignore-installed --no-warn-script-location '
            f'--prefix "{{self.package_folder}}"',
            cwd=self.source_folder,
        )

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        self.cpp_info.includedirs = []
        self.cpp_info.libdirs = []
        pkg = self.package_folder
{SITE_PACKAGES_SNIPPET}
        for env in (self.buildenv_info, self.runenv_info):
{env_lines}            for site in site_packages:
                env.prepend_path("PYTHONPATH", site)
            env.prepend_path("PATH", os.path.join(pkg, "bin"))
            env.prepend_path("PATH", os.path.join(pkg, "Scripts"))
'''


