# Generated by tools/gen_ros_recipes.py from rosdistro. Do not edit by hand.
import glob
import os
import sys
from conan import ConanFile
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import get, replace_in_file
from conan.tools.microsoft import VCVars


class RosPackageConan(ConanFile):
    """package.xml build_type: ament_cmake"""

    name = "rviz_ogre_vendor"
    version = "15.0.13"
    user = "ros-kilted"
    license = 'Apache License 2.0'
    settings = "os", "compiler", "build_type", "arch"
    package_type = "shared-library"

    def layout(self):
        cmake_layout(self, src_folder="src")

    def requirements(self):
        self.requires(
            "freetype/2.13.2",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "glew/2.2.0",
            transitive_headers=True,
            transitive_libs=True,
            run=True,
        )
        self.requires(
            "opengl/system",
            transitive_headers=True,
            transitive_libs=True,
        )
        self.requires(
            "catkin_pkg/1.1.0@ros-kilted",
            run=True,
        )
        self.requires(
            "setuptools/75.8.0@ros-kilted",
            run=True,
        )

    def build_requirements(self):
        self.tool_requires("ament_cmake/2.7.5@ros-kilted")
        self.tool_requires("ament_cmake_vendor_package/2.7.5@ros-kilted")

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        replace_in_file(
            self,
            os.path.join(self.source_folder, 'CMakeLists.txt'),
            '-DFT_DISABLE_HARFBUZZ:BOOL=ON',
            '-DFT_DISABLE_HARFBUZZ:BOOL=ON\n      -DFT_DISABLE_BROTLI:BOOL=ON',
        )
        replace_in_file(
            self,
            os.path.join(self.source_folder, 'CMakeLists.txt'),
            'set(OGRE_CMAKE_ARGS)',
            'set(OGRE_CMAKE_ARGS)\nif(MSVC)\n  set(OGRE_CXX_FLAGS "/D_HAS_AUTO_PTR_ETC=1 ${OGRE_CXX_FLAGS}")\nendif()',
        )
        replace_in_file(
            self,
            os.path.join(self.source_folder, 'CMakeLists.txt'),
            '-DCMAKE_POLICY_VERSION_MINIMUM=3.20',
            '-DCMAKE_POLICY_VERSION_MINIMUM=3.20\n    -DCMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT:BOOL=OFF',
        )
        replace_in_file(
            self,
            os.path.join(self.source_folder, 'CMakeLists.txt'),
            'ament_package(\n  CONFIG_EXTRAS_POST "rviz_ogre_vendor-extras.cmake.in"\n)',
            'if(WIN32)\n  install(CODE "\n    set(_ogre_dest \\"\\${CMAKE_INSTALL_PREFIX}/opt/rviz_ogre_vendor\\")\n    if(NOT EXISTS \\"\\${_ogre_dest}/CMake/OGREConfig.cmake\\")\n      file(GLOB_RECURSE _ogre_configs \\"${CMAKE_CURRENT_BINARY_DIR}/ogre_vendor-prefix/OGREConfig.cmake\\")\n      set(_ogre_root \\"\\")\n      foreach(_ogre_config IN LISTS _ogre_configs)\n        string(REPLACE \\"\\\\\\\\\\" \\"/\\" _ogre_config \\"\\${_ogre_config}\\")\n        if(_ogre_config MATCHES \\"/(install|sdk)/CMake/OGREConfig.cmake$\\")\n          get_filename_component(_ogre_cmake \\"\\${_ogre_config}\\" DIRECTORY)\n          get_filename_component(_ogre_root \\"\\${_ogre_cmake}\\" DIRECTORY)\n          break()\n        endif()\n      endforeach()\n      if(_ogre_root)\n        message(STATUS \\"Installing OGRE from \\${_ogre_root}\\")\n        file(COPY \\"\\${_ogre_root}/\\" DESTINATION \\"\\${_ogre_dest}\\")\n      else()\n        message(FATAL_ERROR \\"OGREConfig.cmake was not installed under ${CMAKE_CURRENT_BINARY_DIR}/ogre_vendor-prefix\\")\n      endif()\n    endif()\n  ")\nendif()\n\nament_package(\n  CONFIG_EXTRAS_POST "rviz_ogre_vendor-extras.cmake.in"\n)',
        )
        replace_in_file(
            self,
            os.path.join(self.source_folder, 'rviz_ogre_vendor-extras.cmake.in'),
            'if(WIN32)\n  set(OGRE_DIR "${@PROJECT_NAME@_DIR}/../../../opt/rviz_ogre_vendor/CMake")\n  set(OGRE_CMAKE_MODULE_DIR "${@PROJECT_NAME@_DIR}/../../../opt/rviz_ogre_vendor/CMake")',
            'if(WIN32)\n  set(_ogre_prefix "${@PROJECT_NAME@_DIR}/../../../opt/rviz_ogre_vendor")\n  get_filename_component(_ogre_prefix "${_ogre_prefix}" ABSOLUTE)\n  get_filename_component(_ogre_pkg "${@PROJECT_NAME@_DIR}/../../.." ABSOLUTE)\n  set(_ogre_candidates\n    "${_ogre_prefix}/CMake"\n    "${_ogre_prefix}/lib/OGRE/cmake"\n    "${_ogre_prefix}/lib/cmake/OGRE"\n    "${_ogre_pkg}/CMake"\n  )\n  set(OGRE_DIR "")\n  foreach(_ogre_candidate IN LISTS _ogre_candidates)\n    if(EXISTS "${_ogre_candidate}/OGREConfig.cmake")\n      set(OGRE_DIR "${_ogre_candidate}")\n      break()\n    endif()\n  endforeach()\n  if(NOT OGRE_DIR)\n    file(GLOB_RECURSE _ogre_configs "${_ogre_pkg}/OGREConfig.cmake")\n    if(_ogre_configs)\n      list(GET _ogre_configs 0 _ogre_config)\n      get_filename_component(OGRE_DIR "${_ogre_config}" DIRECTORY)\n    else()\n      set(OGRE_DIR "${_ogre_prefix}/CMake")\n    endif()\n  endif()\n  set(OGRE_CMAKE_MODULE_DIR "${OGRE_DIR}")',
        )

    def generate(self):
        CMakeDeps(self).generate()

        python = self.conf.get("user.ros2:python", check_type=str) or sys.executable
        python = python.replace("\\", "/")
        python_root = python.rsplit("/", 1)[0]
        tc = CMakeToolchain(self)
        tc.variables["BUILD_TESTING"] = False
        tc.variables["Python3_EXECUTABLE"] = python
        tc.variables["Python3_ROOT_DIR"] = python_root
        tc.variables["Python_EXECUTABLE"] = python
        tc.variables["Python_ROOT_DIR"] = python_root
        tc.generate()
        VCVars(self).generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        pkg = self.package_folder
        # ament on Windows installs RUNTIME (exe and DLL) under bin/.
        self.cpp_info.bindirs = ["bin"]
        self.cpp_info.builddirs.append(pkg)
        self.cpp_info.builddirs.append(os.path.join(pkg, "share", self.name, "cmake"))
        vendored = os.path.join(pkg, "opt", self.name)
        if os.path.isdir(vendored):
            self.cpp_info.builddirs.append(vendored)
            self.cpp_info.bindirs.append(os.path.join(vendored, "bin"))
            self.cpp_info.libdirs.append(os.path.join(vendored, "lib"))
        site_packages = [os.path.join(pkg, "Lib", "site-packages")] + sorted(
            glob.glob(os.path.join(pkg, "lib", "python*", "site-packages")))
        # Not in buildenv: CMakeToolchain already puts every dependency's builddirs in
        # CMAKE_PREFIX_PATH inside conan_toolchain.cmake, a file with no length limit,
        # and one entry per package does not fit in an environment at distro scale.
        self.runenv_info.prepend_path("CMAKE_PREFIX_PATH", pkg)
        for env in (self.buildenv_info, self.runenv_info):
            env.prepend_path("AMENT_PREFIX_PATH", pkg)
            for site in site_packages:
                env.prepend_path("PYTHONPATH", site)
